name: Provision Tool Infra
# run-name: ${{ github.actor }} is learning Github Actions
on: [push, workflow_dispatch]
jobs:
  Provision:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - run: terraform init

